pipeline {
    agent any

    options {
        timeout(time: 20, unit: 'MINUTES')
    }

    environment {
        AWS_REGION = 'eu-central-1'
        ECR_REPO = 'fintrack-app'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker build -t account-service:${BUILD_NUMBER} -f docker/account-service.Dockerfile .'
                sh 'docker build -t payment-service:${BUILD_NUMBER} -f docker/payment-service.Dockerfile .'
            }
        }

        stage('Push to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin $ECR_REPO
                '''
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh 'kubectl apply -f k8s/'
                sh 'kubectl apply -f istio/'
            }
        }

        stage('Smoke Test') {
            steps {
                sh './scripts/healthcheck.sh'
            }
        }
    }

    post {
        failure {
            sh './scripts/rollback.sh'
        }
    }
}